name: Migrate Repository and Secrets

on:
  workflow_dispatch:  # Trigger manually

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up GitHub authentication (using GITHUB_TOKEN for the current repo)
      - name: Set up authentication for GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET }}
        run: |
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV

      # Step 2: Fetch the encryption public key from the source repository
      - name: Get public key for encryption from source repository
        run: |
          source_repo="ShubahshuArya/demo-1"
          api_url="https://api.github.com/repos/${source_repo}/actions/secrets/public-key"
          
          # Get the public key from GitHub API
          public_key_response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $api_url)
          key_id=$(echo "$public_key_response" | jq -r '.key_id')
          public_key=$(echo "$public_key_response" | jq -r '.key')

          echo "key_id=$key_id" >> $GITHUB_ENV
          echo "public_key=$public_key" >> $GITHUB_ENV

      # Step 3: Fetch and print secrets from the source repository
      - name: Fetch and print secrets from source repository
        run: |
          source_repo="ShubahshuArya/demo-1"
          api_url="https://api.github.com/repos/${source_repo}/actions/secrets"
          
          # Fetch the secrets from the source repo
          secrets_list=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $api_url)
          
          # Print the secrets (names and values)
          echo "Fetched the following secrets from the source repo:"
          for secret in $(echo "$secrets_list" | jq -r '.secrets[].name'); do
            # Fetch each secret's value using the GitHub API
            secret_value_response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${source_repo}/actions/secrets/$secret")
            secret_value=$(echo "$secret_value_response" | jq -r '.value')

            # Print the name and value of the secret
            echo "Secret Name: $secret"
            echo "Secret Value: $secret_value"
          done
          
          # Save the secrets list to a file for later use
          echo "$secrets_list" > secrets.json
