name: Migrate Repository and Secrets

on:
  workflow_dispatch:  # Trigger manually

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up GitHub authentication (using GITHUB_TOKEN for the current repo)
      - name: Set up authentication for GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET }}
        run: |
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV

      # Step 4: Fetch secrets from the source repository
      - name: Fetch secrets from source repository
        run: |
          source_repo="ShubahshuArya/demo-1"
          target_repo="ShubahshuArya/demo-2"
          api_url="https://api.github.com/repos/${source_repo}/actions/secrets"
          secrets_list=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $api_url)
          echo "$secrets_list" > secrets.json

      # Step 5: Create secrets in the target repository
      - name: Create secrets in target repository
        run: |
          target_repo="ShubahshuArya/demo-2"
          api_url="https://api.github.com/repos/${target_repo}/actions/secrets"
          
          # Loop through each secret and create it in the target repository
          for secret in $(jq -r '.secrets[].name' secrets.json); do
            secret_value=$(jq -r ".secrets[] | select(.name==\"$secret\") | .value" secrets.json)
            
            # Create secret in the target repository
            curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
              -d "{\"encrypted_value\":\"$secret_value\"}" \
              $api_url/$secret
            echo "Secret $secret created in $target_repo"
          done

      # Step 6: Migrate environment variables (manually, since GitHub Actions doesn't support dynamic references for secrets)
      - name: Migrate environment variables manually
        run: |
          # Replace the following with your actual environment variable names
          # Ensure the variables are stored as secrets first if needed
          
          # Example of manually passing environment variables from secrets:
          echo "VAR1=${{ secrets.VAR1 }}" >> $GITHUB_ENV
          echo "VAR2=${{ secrets.VAR2 }}" >> $GITHUB_ENV

          # Example of passing other environment variables directly (not as secrets):
          echo "MY_ENV_VAR=some_value" >> $GITHUB_ENV
          echo "Migrating environment variables"
